### ISSUE TITLE
proj4string from grid

### ISSUE THREAD

**Issue by AdamSchnapp** [eengl/pytdlpack#6]
Hi Eric,

It would be nice to be able to get a proj4 string from a gridded tdlpack record for interoperability with other software packages.

**Comment by eengl** [comment]
That is reasonable!  I will add this as a class attribute for a gridded TdlpackRecord.  We'll have to test for the existence of pyproj module up front and is it is not available, then just return None.  I'd rather not have pytdlpack have a package dependency on pyproj.

**Comment by eengl** [comment]
@AdamSchnapp -- Would you rather an instance of the pyproj.Proj class?

**Comment by eengl** [comment]
I have added this feature.  TdlpackRecord will have a class attribute proj_string that will hold the PROJ string for gridded TDLPACK records.  The string is generated from pyproj.Proj.definition_string().

**Comment by AdamSchnapp** [comment]
Awesome!
